# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "3.8.0"
  lib_version: ${{ version | split('.post') | first }}

package:
  name: types-aiobotocore-s3
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/types-aiobotocore-s3/types_aiobotocore_s3-${{ version }}.tar.gz
  sha256: 45d43768cf576cc7c11097db6c4806c3acc5da8dca0f0e0e13b7589dde8db89a

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - aiobotocore
    - typing_extensions

tests:
  - python:
      imports:
        - types_aiobotocore_s3
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/youtype/mypy_boto3_builder
  summary: Type annotations for aiobotocore.S3 ${{ lib_version }} service generated with mypy-boto3-builder
  license: MIT
  license_file: LICENSE
  documentation: https://youtype.github.io/types_aiobotocore_docs/
  repository: https://github.com/youtype/mypy_boto3_builder

extra:
  recipe-maintainers:
    - vemel
    - fhoehle
